#! /bin/bash

#docker login https://registry.redhat.io

docker pull registry.redhat.io/openshift3/apb-base:3.11
docker pull registry.redhat.io/openshift3/apb-tools:3.11
docker pull registry.redhat.io/openshift3/automation-broker-apb:3.11
docker pull registry.redhat.io/openshift3/csi-attacher:3.11
docker pull registry.redhat.io/openshift3/csi-driver-registrar:3.11
docker pull registry.redhat.io/openshift3/csi-livenessprobe:3.11
docker pull registry.redhat.io/openshift3/csi-provisioner:3.11
docker pull registry.redhat.io/openshift3/grafana:3.11
docker pull registry.redhat.io/openshift3/local-storage-provisioner:3.11
docker pull registry.redhat.io/openshift3/manila-provisioner:3.11
docker pull registry.redhat.io/openshift3/mariadb-apb:3.11
docker pull registry.redhat.io/openshift3/mediawiki:3.11
docker pull registry.redhat.io/openshift3/mediawiki-apb:3.11
docker pull registry.redhat.io/openshift3/mysql-apb:3.11
docker pull registry.redhat.io/openshift3/ose-ansible-service-broker:3.11
docker pull registry.redhat.io/openshift3/ose-cli:3.11
docker pull registry.redhat.io/openshift3/ose-cluster-autoscaler:3.11
docker pull registry.redhat.io/openshift3/ose-cluster-capacity:3.11
docker pull registry.redhat.io/openshift3/ose-cluster-monitoring-operator:3.11
docker pull registry.redhat.io/openshift3/ose-console:3.11
docker pull registry.redhat.io/openshift3/ose-configmap-reloader:3.11
docker pull registry.redhat.io/openshift3/ose-control-plane:3.11
docker pull registry.redhat.io/openshift3/ose-deployer:3.11
docker pull registry.redhat.io/openshift3/ose-descheduler:3.11
docker pull registry.redhat.io/openshift3/ose-docker-builder:3.11
docker pull registry.redhat.io/openshift3/ose-docker-registry:3.11
docker pull registry.redhat.io/openshift3/ose-efs-provisioner:3.11
docker pull registry.redhat.io/openshift3/ose-egress-dns-proxy:3.11
docker pull registry.redhat.io/openshift3/ose-egress-http-proxy:3.11
docker pull registry.redhat.io/openshift3/ose-egress-router:3.11
docker pull registry.redhat.io/openshift3/ose-haproxy-router:3.11
docker pull registry.redhat.io/openshift3/ose-hyperkube:3.11
docker pull registry.redhat.io/openshift3/ose-hypershift:3.11
docker pull registry.redhat.io/openshift3/ose-keepalived-ipfailover:3.11
docker pull registry.redhat.io/openshift3/ose-kube-rbac-proxy:3.11
docker pull registry.redhat.io/openshift3/ose-kube-state-metrics:3.11
docker pull registry.redhat.io/openshift3/ose-metrics-server:3.11
docker pull registry.redhat.io/openshift3/ose-node:3.11
docker pull registry.redhat.io/openshift3/ose-node-problem-detector:3.11
docker pull registry.redhat.io/openshift3/ose-operator-lifecycle-manager:3.11
docker pull registry.redhat.io/openshift3/ose-ovn-kubernetes:3.11
docker pull registry.redhat.io/openshift3/ose-pod:3.11
docker pull registry.redhat.io/openshift3/ose-prometheus-config-reloader:3.11
docker pull registry.redhat.io/openshift3/ose-prometheus-operator:3.11
docker pull registry.redhat.io/openshift3/ose-recycler:3.11
docker pull registry.redhat.io/openshift3/ose-service-catalog:3.11
docker pull registry.redhat.io/openshift3/ose-template-service-broker:3.11
docker pull registry.redhat.io/openshift3/ose-tests:3.11
docker pull registry.redhat.io/openshift3/ose-web-console:3.11
docker pull registry.redhat.io/openshift3/postgresql-apb:3.11
docker pull registry.redhat.io/openshift3/registry-console:3.11
docker pull registry.redhat.io/openshift3/snapshot-controller:3.11
docker pull registry.redhat.io/openshift3/snapshot-provisioner:3.11
docker pull registry.redhat.io/openshift3/ose-efs-provisioner:3.11
docker pull registry.redhat.io/openshift3/metrics-cassandra:3.11
docker pull registry.redhat.io/openshift3/metrics-hawkular-metrics:3.11
docker pull registry.redhat.io/openshift3/metrics-hawkular-openshift-agent:3.11
docker pull registry.redhat.io/openshift3/metrics-heapster:3.11
docker pull registry.redhat.io/openshift3/metrics-schema-installer:3.11
docker pull registry.redhat.io/openshift3/oauth-proxy:3.11
docker pull registry.redhat.io/openshift3/ose-logging-curator5:3.11
docker pull registry.redhat.io/openshift3/ose-logging-elasticsearch5:3.11
docker pull registry.redhat.io/openshift3/ose-logging-eventrouter:3.11
docker pull registry.redhat.io/openshift3/ose-logging-fluentd:3.11
docker pull registry.redhat.io/openshift3/ose-logging-kibana5:3.11
docker pull registry.redhat.io/openshift3/prometheus:3.11
docker pull registry.redhat.io/openshift3/prometheus-alertmanager:3.11
docker pull registry.redhat.io/openshift3/prometheus-node-exporter:3.11
docker pull registry.redhat.io/rhel7/etcd:3.2.22