parameter_defaults:
  CephPoolDefaultSize: 3
  CephPoolDefaultPgNum: 64
  CephConfigOverrides:
    journal_size: 5120
    max_open_files: 131072
    osd_recovery_op_priority: 3
    osd_recovery_max_active: 3
    osd_max_backfills: 1
  CephAnsibleDisksConfig:
    devices:
      - /dev/vdb
      - /dev/vdc
      - /dev/vdd
    journal_collocation: true
    osd_scenario: collocated
    osd_objectore: filestore


#  CephPools:
#    - {"name": backups, "pg_num": 512, "pgp_num": 512}
#    - {"name": volumes, "pg_num": 1024, "pgp_num": 1024, "rule_name": 'replicated_rule', "erasure_profile": '', "expected_num_objects": 6000}
#    - {"name": vms, "pg_num": 512, "pgp_num": 512}
#    - {"name": images, "pg_num": 128, "pgp_num": 128}
#  CephAnsibleExtraConfig:
#    ceph_osd_docker_memory_limit: 3g
#    ceph_osd_docker_cpu_limit: 1
